version: '3'
services:
  flask:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PIPELINE_DB=redis://redis:6379/1
    volumes:
      - shared_volume:/tmp
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "9000:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - flask

  celery-worker:
    build:
      context: ./src/detector
      dockerfile: Dockerfile
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PIPELINE_DB=redis://redis:6379/1
    volumes:
      - shared_volume:/tmp
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  shared_volume:
